# Generated by Django 3.1.2 on 2020-10-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('major', models.CharField(blank=True, max_length=10, null=True)),
                ('minor', models.CharField(blank=True, max_length=10, null=True)),
                ('son_gorulme', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True, verbose_name='Oda İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='AlgilayiciModul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True, verbose_name='Algılayıcı İsmi')),
                ('beacon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.beacon')),
                ('oda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.oda')),
            ],
        ),
    ]
