# Generated by Django 2.2.16 on 2020-10-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algilayicimodul',
            options={'verbose_name_plural': 'Algılayıcı Modül'},
        ),
        migrations.AlterModelOptions(
            name='beacon',
            options={'verbose_name_plural': 'Beacon'},
        ),
        migrations.AlterModelOptions(
            name='oda',
            options={'verbose_name_plural': 'Oda'},
        ),
    ]
