# Generated by Django 2.2.16 on 2020-11-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_auto_20201030_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algilayicimodul',
            name='beacon',
        ),
        migrations.AddField(
            model_name='beacon',
            name='modul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.AlgilayiciModul'),
        ),
    ]
