# Generated by Django 3.1.2 on 2020-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=50, null=True, verbose_name='Soyisim')),
                ('tc_kimlik_no', models.CharField(max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('cinsiyet', models.CharField(choices=[(None, 'Cinsiyet Seçiniz'), ('bos', 'Belirtmek İstemiyorum'), ('erkek', 'Erkek'), ('kadin', 'Kadın')], max_length=20, null=True, verbose_name='Cinsiyet')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
            ],
        ),
    ]
