# Generated by Django 3.1.2 on 2020-10-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personeller',
            options={'verbose_name_plural': 'Personeller'},
        ),
        migrations.AddField(
            model_name='personeller',
            name='beacon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.beacon'),
        ),
    ]
