# Generated by Django 2.2.16 on 2020-11-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_gorevler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorevler',
            options={'verbose_name_plural': 'Görevler'},
        ),
    ]
