# Generated by Django 2.2.16 on 2021-03-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0004_auto_20201106_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personeller',
            options={'ordering': ['isim'], 'verbose_name_plural': 'Personeller'},
        ),
        migrations.AlterField(
            model_name='personeller',
            name='beacon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.Beacon', unique=True),
        ),
    ]
