# Generated by Django 2.2.16 on 2021-03-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0005_auto_20210310_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='personeller',
            name='iban',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='IBAN Bilgisi'),
        ),
        migrations.AddField(
            model_name='personeller',
            name='kan_grubu',
            field=models.CharField(choices=[(None, 'Kan Grubu Seçini'), ('bos', 'Belirtmek İstemiyorum'), ('0RhPozitif', '0 Rh+'), ('0RhNegatif', '0 Rh-'), ('abRhPozitif', 'AB Rh+'), ('abRhNegatif', 'AB Rh-'), ('aRhPozitif', 'A Rh+'), ('aRhNegatif', 'A Rh-'), ('bRhPozitif', 'B Rh+'), ('bRhNegatif', 'B Rh-')], max_length=9, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='personeller',
            name='ssk_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SSK No'),
        ),
        migrations.AddField(
            model_name='personeller',
            name='unvan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='personeller',
            name='beacon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.Beacon'),
        ),
    ]
