# Generated by Django 2.2.16 on 2021-03-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0006_auto_20210310_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeller',
            name='kan_grubu',
            field=models.CharField(choices=[(None, 'Kan Grubu Seçini'), ('bos', 'Belirtmek İstemiyorum'), ('0RhPozitif', '0 Rh+'), ('0RhNegatif', '0 Rh-'), ('abRhPozitif', 'AB Rh+'), ('abRhNegatif', 'AB Rh-'), ('aRhPozitif', 'A Rh+'), ('aRhNegatif', 'A Rh-'), ('bRhPozitif', 'B Rh+'), ('bRhNegatif', 'B Rh-')], max_length=30, null=True, verbose_name='Kan Grubu'),
        ),
    ]
