# Generated by Django 2.2.16 on 2021-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0007_auto_20210310_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeller',
            name='tc_kimlik_no',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='TC Kimlik No'),
        ),
    ]
