# Generated by Django 2.2.16 on 2021-03-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personel', '0008_auto_20210310_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='personeller',
            name='departman',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departman'),
        ),
        migrations.AddField(
            model_name='personeller',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
