# Generated by Django 2.2.17 on 2021-09-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0010_auto_20210929_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Kullanıcı Profiller'},
        ),
    ]
